-- HACK: LOAD PLUGIN CONFIGS
require('configs.vim')
require('configs.telescope')
require('configs.treesitter')
require('configs.lsp')
require('configs.autocompletion')
require('configs.gitsigns')
require('configs.harpoon')
require('configs.dap')
require('configs.colorscheme')
require('configs.neotree')
require('configs.indent')
require('configs.live-preview')
require('configs.obsidian')
-- require('configs.ccc')
require('configs.lualine')
